WomenMarket.App/Areas/Admin/Controllers/HomeAdminController.cs
namespace WomenMarket.App.Areas.Admin.Controllers
{
    using System.Web.Mvc;
    using Data.UnitOfWork;

    public class HomeAdminController : BaseAdminController
    {
        public HomeAdminController(IWomenMarketData data) 
            : base(data)
        {
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        
    }
}

WomenMarket.App/Controllers/ProductsController.cs
namespace WomenMarket.App.Controllers
{
    using System.Web.Mvc;
    using Services.Interfaces;
    using Data.UnitOfWork;
    using WomenMarket.Models.EntityModels;
    using System.Collections.Generic;
    using WomenMarket.Models.ViewModels;
    using PagedList;

    [RoutePrefix("products")]
    public class ProductsController : BaseController
    {
        private IProductsService service;

        public ProductsController(IWomenMarketData data, IProductsService service) 
            : base(data)
        {
            this.service = service;
        }

        public ProductsController(IWomenMarketData data, User user) 
            : base(data, user)
        {
        }

        [HttpGet]
        [Route("{category?}")]
        public ActionResult All(string category, int? page)
        {
            IEnumerable<ProductViewModel>  products = category == null ? this.service.GetAllProducts() : this.service.GetFilteredProducts(category);

            int pageSize = 3;
            int pageNumber = (page ?? 1);

            return View(products.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        [Route("search")]
        public ActionResult Search(string currentFilter, string product, int? page)
        {
            if (product != null)
            {
                page = 1;
            }
            else
            {
                product = currentFilter;

            }

            ViewBag.CurrentFilter = product;

            var products = this.service.GetSearchedProducts(product);

            int pageSize = 3;
            int pageNumber = (page ?? 1);

            return this.View(products.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        [Route("farm/{farmName}")]
        public ActionResult ByFarm(string farmName, int? page)
        {
            var products = this.service.GetProductsByFarm(farmName);

            int pageSize = 3;
            int pageNumber = (page ?? 1);

            return View(products.ToPagedList(pageNumber, pageSize));
        }
    }
}

WomenMarket.App/Controllers/ProfileController.cs
namespace WomenMarket.App.Controllers
{
    using System.Web.Mvc;
    using Data.UnitOfWork;
    using System.Collections.Generic;
    using PagedList;
    using WomenMarket.Models.BindingModels;
    using WomenMarket.Models.EntityModels;
    using WomenMarket.Models.ViewModels;
    using Services.Interfaces;

    public class ProfileController : BaseController
    {
        private IProfileService service;

        public ProfileController(IWomenMarketData data, IProfileService service) 
            : base(data)
        {
            this.service = service;
        }

        public ProfileController(IWomenMarketData data, User user) 
            : base(data, user)
        {
        }

        [HttpGet]
        public ActionResult Index()
        {
            UserViewModel viewModel = service.GetProfile(this.UserProfile);

            TempData["controllerName"] = this.ControllerContext.RouteData.Values["controller"].ToString();

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Edit()
        {
            UserViewModel viewModel = service.GetProfile(this.UserProfile);

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserBindingModel model)
        {
            if (model != null && ModelState.IsValid)
            {
                service.EditUser(this.UserProfile, model);

                string controller = TempData["controllerName"].ToString();

                return RedirectToAction("Index", controller, routeValues: new { area = "" });

            }

            return this.View();
        }

        [HttpGet]
        public ActionResult MyOrders(int? page)
        {
            IEnumerable<MyOrderViewModel> viewModels = service.GetMyOrders(this.UserProfile);

            int pageSize = 3;
            int pageNumber = (page ?? 1);

            return View(viewModels.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public PartialViewResult _OrdersByStatusPartial(string status, int? page)
        {            
            IEnumerable<MyOrderViewModel> viewModels = service.GetOrdersByStatus(this.UserProfile, status);

            int pageSize = 3;
            int pageNumber = (page ?? 1);

            return PartialView(viewModels.ToPagedList(pageNumber, pageSize));
        }
    }
}

WomenMarket.App/Controllers/ShoppingCartController.cs
namespace WomenMarket.App.Controllers
{
    using System.Web.Mvc;
    using Data.UnitOfWork;
    using System.Collections.Generic;
    using WomenMarket.Models.EntityModels;
    using Services.Interfaces;
    using WomenMarket.Models.ViewModels;

    [Authorize(Roles = "User")]
    [RoutePrefix("shoppingcart")]
    public class ShoppingCartController : BaseController
    {
        private IShoppingCartService service;
        private IProfileService userService;

        public ShoppingCartController(IWomenMarketData data, IShoppingCartService service, IProfileService userService) 
            : base(data)
        {
            this.service = service;
            this.userService = userService;
        }

        public ShoppingCartController(IWomenMarketData data, User user) 
            : base(data, user)
        {
        }

        [HttpGet]
        public ActionResult Index()
        {
            if (!service.IsProfileComplete(this.UserProfile))
            {
                TempData["controllerName"] = this.ControllerContext.RouteData.Values["controller"].ToString();
                return this.RedirectToAction("Edit", "Profile");
            }

            IEnumerable<ShoppingCartProductViewModel> carts = service.MyShoppingCart(this.UserProfile);

            return View(carts);
        }

        [HttpGet]
        [Route("addproduct/{id}")]
        public ActionResult AddProduct(int id)
        {
            Product product = service.GetProduct(id);

            ShoppingCart cart = service.GetShoppingCart(this.UserProfile);

            service.AddToShoppingCart(cart, product);

            return this.RedirectToAction("All", "Products");
        }

        [HttpGet]
        [Route("cart/{cartId}/removeproduct/{id}")]
        public ActionResult RemoveProduct(int cartId, int id)
        {
            Product product = service.GetProduct(id);

            ShoppingCart cart = service.GetCurrentShoppingCart(cartId);

            service.RemoveFromShoppingCart(cart, product);

            IEnumerable<ShoppingCartProductViewModel> carts = service.MyShoppingCart(this.UserProfile);

            return this.PartialView("_ShoppingCartPartial", carts);
        }

        [HttpGet]
        [Route("cart/{cartId}/decreaseproductunits/{id}")]
        public ActionResult DecreaseProductUnits(int cartId, int id)
        {
            Product product = service.GetProduct(id);

            ShoppingCart cart = service.GetCurrentShoppingCart(cartId);

            service.DecreaseProductUnitsFromShoppingCart(cart, product);

            IEnumerable<ShoppingCartProductViewModel> carts = service.MyShoppingCart(this.UserProfile);

            return this.PartialView("_ShoppingCartPartial", carts);
        }

        [HttpGet]
        [Route("cart/{cartId}/increaseproductunits/{id}")]
        public ActionResult IncreaseProductUnits(int cartId, int id)
        {
            Product product = service.GetProduct(id);

            ShoppingCart cart = service.GetCurrentShoppingCart(cartId);

            service.IncreaseProductUnitsFromShoppingCart(cart, product);

            IEnumerable<ShoppingCartProductViewModel> carts = service.MyShoppingCart(this.UserProfile);

            return this.PartialView("_ShoppingCartPartial", carts);
        }

        [HttpGet]
        [Route("placeorder/{id}")]
        public ActionResult PlaceOrder(int id, decimal totalAmount)
        {
            if (!service.IsProfileComplete(this.UserProfile))
            {
                UserViewModel viewModel = userService.GetProfile(this.UserProfile);
                return this.PartialView("_EditProfilePartial", viewModel);
            }

            service.MakeAnOrder(id, totalAmount);

            IEnumerable<ShoppingCartProductViewModel> carts = service.MyShoppingCart(this.UserProfile);

            return this.PartialView("_ShoppingCartPartial", carts);
        }

        [HttpGet]
        public ActionResult Products(int id)
        {
            IEnumerable<ShoppingCartProduct> viewModels = service.GetOrderProducts(id);

            return View(viewModels);
        }
    }
}

WomenMarket.App/Views/Shared/_EditProfilePartial.cshtml
@using WomenMarket.App.Extensions
@using WomenMarket.Models.ViewModels
@model UserViewModel
@{
    ViewBag.Title = "Edit profile";
}

<div class="container">
    
    <div class="alert alert-dismissible alert-info" style="margin-top: 2vh;">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <p>Please fill out all your profile information before placing an order.</p>
    </div>
    

    @using (Html.BeginForm("Edit", "Profile", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        <h2 class="form-signin-heading">@ViewBag.Title</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.Id)
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Address, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.PhoneNumber, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.PhoneNumber, new { htmlAttributes = new { @class = "form-control", placeholder = "0888610285" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ImageUrl, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.Submit("Edit")
                @Html.ActionLink("Cancel", "Index", "Profile", new { area = "" }, new { @class = "btn btn-danger" })
            </div>
        </div>
    }
</div>

WomenMarket.App/Views/Shared/_Layout.cshtml
@using WomenMarket.App.Extensions
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Women's Market</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Women's Market", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @{
                        if (User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink("Admin", "Index", "HomeAdmin", routeValues: new { area = "Admin" }, htmlAttributes: null)</li>
                        }
                    }
                    <li>@Html.ActionLink("Farms", "All", "Farms")</li>
                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            Products <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                            <li role="presentation">@Html.ActionLink("All", "All", "Products", routeValues: new { area = "", category = "" }, htmlAttributes: null)</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    
<div class="container-fluid">
    <div id="notifications" style="display: none;"></div>
    @RenderBody()
</div>
    <footer class="footer-distributed">
        <div class="footer-left">
            <h3>Women's<span> Market</span></h3>
            <p class="footer-links">
                @Html.ActionLink("Home", "Index", "Home")
                ·
                @Html.ActionLink("Farms", "All", "Farms")
                ·
                @Html.ActionLink("Products", "All", "Products")
                ·
                @if (User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Admin", "Index", "HomeAdmin", routeValues: new { area = "Admin" }, htmlAttributes: null)
                }
                else
                {
                    @Html.ActionLink("Shopping cart", "Index", "ShoppingCart")
                }
            </p>
            <p class="footer-company-name">Women's Market &copy; 2017</p>
        </div>
        <div class="footer-center">
            <div>
                <i class="fa fa-map-marker"></i>
                <p><span>21 Solunska str.</span> Sofia, Bulgaria</p>
            </div>
            <div>
                <i class="fa fa-phone"></i>
                <p>+359 889 780 321</p>
            </div>
            <div>
                <i class="fa fa-envelope"></i>
                <p>@Html.EmailTextBox("konstantin1230@yahoo.com")</p>
            </div>
        </div>
        <div class="footer-right">
            <p class="footer-company-about">
                <span>About the company</span>
                One of the biggest markets in the country.
            </p>
            <div class="footer-icons">
                <a href="https://www.facebook.com/konstantin.kirchev" target="_blank"><i class="fa fa-facebook"></i></a>
                <a href="https://twitter.com/konstantin1230" target="_blank"><i class="fa fa-twitter"></i></a>
                <a href="https://www.linkedin.com/in/konstantinkirchev" target="_blank"><i class="fa fa-linkedin"></i></a>
                <a href="https://github.com/KonstantinKirchev/" target="_blank"><i class="fa fa-github"></i></a>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/signalr")
    @Scripts.Render("~/signalr/hubs")
    @Scripts.Render("~/bundles/bootstrap")
    <script>
            $(document)
                .ready(function () {
                    $.ajax({
                        url: '@Url.Action("GetCategories", "Categories", new { Area = "Admin" })',
                        type: "GET",
                        success: function (result) {
                            
                            $.each(result, function (key, value) {
                                var category = value.Name;
                                var li = $('<li role="presentation">');
                                var link = $('<a href="/products/' + category.toLowerCase() + '">' + category + '</div>');
                                li.append(link);
                                $(".dropdown ul").append(li);
                            });
                        }
                    });

                    var notificationsHub = $.connection.notifications;
                    notificationsHub.client.receiveNotification = function (type, notification) {
                        var notificationElement = $("<div>")
                            .addClass("alert alert-dismissible alert-" + type)
                            .html("<button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>" +
                                notification);
                        $("#notifications").append(notificationElement);

                        var notesCount = parseInt($(".circle-cell").html());
                        $(".circle-cell").html(notesCount + 1);

                        $(".close")
                            .click(function () {
                                var count = $("#notifications div").length;
                                $(".circle-cell").html(count - 1);
                            });

                        $("#notes")
                            .click(function () {
                                if ($('#notifications').css('display') == 'none') {
                                    $('#notifications')
                                        .css({
                                            display: 'block'
                                        });
                                } else {
                                    $('#notifications')
                                        .css({
                                            display: 'none'
                                        });
                                }

                            });
                    }

                    $.connection.hub.start();
                });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

WomenMarket.App/Views/Shared/_OrdersByStatusPartial.cshtml
@using WomenMarket.Models.ViewModels
@model IPagedList<MyOrderViewModel>

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Order number</th>
                <th>Date of order</th>
                <th>Date of delivery</th>
                <th>Products</th>
                <th>Total amount</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @Html.DisplayFor(myOrder => myOrder)
        </tbody>
    </table>
</div>

@if (Model.PageCount > 1)
{
    @Html.PagedListPager(Model, page => Url.Action("MyOrders", "Profile", new { page }))
}

WomenMarket.App/Views/Shared/_ProductResult.cshtml
@Html.DisplayFor(product => product)

WomenMarket.App/Views/Shared/_ShoppingCartPartial.cshtml
@using WomenMarket.Models.ViewModels
@model IEnumerable<ShoppingCartProductViewModel>

@if (Model == null || !Model.Any())
{
    <div class="container" style="text-align: center; color: red;">
        <h1>You don't have any products in your shopping cart.</h1>
    </div>
}
else
{
    <div class="container">
        <div hidden="hidden" id="removeProduct" class="alert alert-dismissible alert-danger">The product was removed!</div>
        <div hidden="hidden" id="increaseQuantity" class="alert alert-dismissible alert-success">The product quantity was increased!</div>
        <div hidden="hidden" id="decreaseQuantity" class="alert alert-dismissible alert-danger">The product quantity was decreased!</div>
        <div hidden="hidden" id="ordered" class="alert alert-dismissible alert-success">Your order was successfully send!</div>
        <h1 style="text-align: center;">@ViewBag.Title</h1>
        <div class="cart" id="myCart">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        decimal total = 0.00m;
                    }
                    @foreach (var cart in Model)
                    {
                        ViewBag.ShoppingCartId = cart.ShoppingCartId;

                        total += (cart.Product.Price * cart.Units);
                        <tr>
                            <td>@cart.Product.Name</td>
                            <td>
                                @Ajax.ActionLink("-", "DecreaseProductUnits", "ShoppingCart", new { area = "", cartId = cart.ShoppingCartId, id = cart.ProductId }, new AjaxOptions()
                           {
                               HttpMethod = "GET",
                               UpdateTargetId = "myCart",
                               InsertionMode = InsertionMode.Replace,
                               LoadingElementId = "decreaseQuantity",
                               LoadingElementDuration = 1000
                           }, new { @class = "btn btn-danger btn-xs" })

                                <span>@cart.Units</span>

                                @Ajax.ActionLink("+", "IncreaseProductUnits", "ShoppingCart", new { area = "", cartId = cart.ShoppingCartId, id = cart.ProductId }, new AjaxOptions()
                           {
                               HttpMethod = "GET",
                               UpdateTargetId = "myCart",
                               InsertionMode = InsertionMode.Replace,
                               LoadingElementId = "increaseQuantity",
                               LoadingElementDuration = 1000
                           }, new { @class = "btn btn-success btn-xs" })
                            </td>
                            <td>@(cart.Product.Price * cart.Units)</td>
                            <td>
                                @Ajax.ActionLink("Remove", "RemoveProduct", "ShoppingCart", new { area = "", cartId = cart.ShoppingCartId, id = cart.ProductId }, new AjaxOptions()
                           {
                               HttpMethod = "GET",
                               UpdateTargetId = "myCart",
                               InsertionMode = InsertionMode.Replace,
                               LoadingElementId = "removeProduct",
                               LoadingElementDuration = 1000,
                               Confirm = "Are you sure you want to remove this product from your shopping cart?"
                           }, new { @class = "btn btn-danger btn-sm" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <h2>Total: @total lv.</h2>
            @Ajax.ActionLink("Order now", "PlaceOrder", "ShoppingCart", new { area = "", id = ViewBag.ShoppingCartId, totalAmount = total }, new AjaxOptions()
       {
           HttpMethod = "GET",
           UpdateTargetId = "myCart",
           InsertionMode = InsertionMode.Replace,
           LoadingElementId = "ordered",
           LoadingElementDuration = 2000
       }, new { @class = "btn btn-success" })
            <br>
            <br>
        </div>

    </div>
}