WomenMarket.App/Areas/Admin/Controllers/HomeAdminController.cs
namespace WomenMarket.App.Areas.Admin.Controllers
{
    using System.Web.Mvc;
    using Data.UnitOfWork;

    public class HomeAdminController : BaseAdminController
    {
        public HomeAdminController(IWomenMarketData data) 
            : base(data)
        {
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        
    }
}

WomenMarket.App/Controllers/FarmsController.cs
namespace WomenMarket.App.Controllers
{
    using System.Web.Mvc;
    using Data.UnitOfWork;
    using WomenMarket.Models.EntityModels;
    using PagedList;
    using Services.Interfaces;

    [RoutePrefix("farms")]
    public class FarmsController : BaseController
    {
        private IFarmsService service;

        public FarmsController(IWomenMarketData data, IFarmsService service) 
            : base(data)
        {
            this.service = service;
        }

        public FarmsController(IWomenMarketData data, User user) 
            : base(data, user)
        {
        }

        [HttpGet]
        [Route]
        //[OutputCache(Duration = 60, Location = OutputCacheLocation.ServerAndClient)]
        public ActionResult All(int? page)
        {
            var farms = this.service.GetAllFarms();

            int pageSize = 4;
            int pageNumber = (page ?? 1);

            return View(farms.ToPagedList(pageNumber, pageSize));
        }
    }
}

WomenMarket.App/Controllers/ProductsController.cs
namespace WomenMarket.App.Controllers
{
    using System.Web.Mvc;
    using Services.Interfaces;
    using Data.UnitOfWork;
    using WomenMarket.Models.EntityModels;
    using System.Collections.Generic;
    using WomenMarket.Models.ViewModels;
    using PagedList;

    [RoutePrefix("products")]
    public class ProductsController : BaseController
    {
        private IProductsService service;

        public ProductsController(IWomenMarketData data, IProductsService service) 
            : base(data)
        {
            this.service = service;
        }

        public ProductsController(IWomenMarketData data, User user) 
            : base(data, user)
        {
        }

        [HttpGet]
        [Route("{category?}")]
        public ActionResult All(string category, int? page)
        {
            IEnumerable<ProductViewModel>  products = category == null ? this.service.GetAllProducts() : this.service.GetFilteredProducts(category);

            int pageSize = 3;
            int pageNumber = (page ?? 1);

            return View(products.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        [Route("search")]
        public ActionResult Search(string currentFilter, string product, int? page)
        {
            if (product != null)
            {
                page = 1;
            }
            else
            {
                product = currentFilter;

            }

            ViewBag.CurrentFilter = product;

            var products = this.service.GetSearchedProducts(product);

            int pageSize = 3;
            int pageNumber = (page ?? 1);

            return this.View(products.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        [Route("farm/{farmName}")]
        public ActionResult ByFarm(string farmName, int? page)
        {
            var products = this.service.GetProductsByFarm(farmName);

            int pageSize = 3;
            int pageNumber = (page ?? 1);

            return View(products.ToPagedList(pageNumber, pageSize));
        }
    }
}

WomenMarket.App/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Women's Market</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Admin Panel", "Index", "HomeAdmin", new { area = "Admin" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Orders", "Index", "Orders")</li>
                    <li>@Html.ActionLink("Categories", "Index", "Categories")</li>
                    <li>@Html.ActionLink("Add farm", "Add", "Farms")</li>
                    <li>@Html.ActionLink("Add product", "Add", "Products")</li>
                    <li>@Html.ActionLink("New notification", "Index", "Notifications")</li>
                    <li>@Html.ActionLink("Back To Site", "Index", "Home", routeValues: new { area = "" }, htmlAttributes: null)</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Women's Market</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>